src/Web/LearnFast.Web/Controllers/CourseController.cs
namespace LearnFast.Web.Controllers
{
    using System;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Braintree;
    using Ganss.Xss;
    using LearnFast.Data.Models;
    using LearnFast.Services;
    using LearnFast.Services.Data;
    using LearnFast.Services.Data.CategoryService;
    using LearnFast.Services.Data.CourseService;
    using LearnFast.Services.Data.DifficultyService;
    using LearnFast.Services.Data.LanguageService;
    using LearnFast.Web.ViewModels.ApplicationUser;
    using LearnFast.Web.ViewModels.Course;
    using LearnFast.Web.ViewModels.Filter;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class CourseController : BaseController
    {
        private const string EmptyView = "Empty";
        private const string CoursesView = "Courses";
        private const string CategoryController = "Category";

        private readonly ICourseService courseService;
        private readonly IFilterCourse filterCourse;
        private readonly ILanguageService languageService;
        private readonly ICategoryService categoryService;
        private readonly IDifficultyService difficultyService;
        private readonly IBraintreeService braintreeService;
        private readonly IUserService userService;

        public CourseController(
            ICourseService courseService,
            IFilterCourse filterCourse,
            ILanguageService languageService,
            ICategoryService categoryService,
            IDifficultyService difficultyService,
            IBraintreeService braintreeService,
            IUserService userService)
        {
            this.courseService = courseService;
            this.filterCourse = filterCourse;
            this.languageService = languageService;
            this.categoryService = categoryService;
            this.difficultyService = difficultyService;
            this.braintreeService = braintreeService;
            this.userService = userService;
        }

        public static string CourseNameController => nameof(CourseController).Replace("Controller", string.Empty);

        public static string DetailsActionName => nameof(Details);

        public IActionResult IsPaid()
        {
            return this.View();
        }

        public async Task<IActionResult> Create(bool isPaid = false)
        {
            var user = await this.userService.GetLoggedUserAsync();

            if (user.StripeId == null && isPaid == true)
            {
                return this.RedirectToAction(nameof(this.IsPaid), CourseNameController);
            }

            var model = new ImportCourseModel();
            model.IsFree = isPaid;
            await this.LoadingBaseParameters(model);

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ImportCourseModel model)
        {
            if (!this.ModelState.IsValid)
            {
                await this.LoadingBaseParameters(model);

                return this.View(model);
            }

            try
            {
                var course = await this.courseService.AddCourseAsync(model);
                var courseId = course.Id;

                return this.RedirectToAction(nameof(this.Details), new { id = courseId });
            }
            catch (Exception ex)
            {
                return this.BadRequest(ex.Message);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var userId = await this.userService.GetLoggedUserIdAsync();
            try
            {
                await this.courseService.DeleteCourseByIdAsync(id, userId);
                return this.RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return this.BadRequest(ex.Message);
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            var userId = await this.userService.GetLoggedUserIdAsync();

            try
            {
                var model = await this.filterCourse.GetCourseByIdAsync<ImportCourseModel>(id);

                if (model.Owner.Id != userId)
                {
                    return this.Forbid();
                }

                await this.LoadingBaseParameters(model);

                return this.View(model);
            }
            catch (Exception ex)
            {
                return this.NotFound(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ImportCourseModel model)
        {
            if (!this.ModelState.IsValid)
            {
                await this.LoadingBaseParameters(model);

                return this.View(model);
            }

            try
            {
                var userId = await this.userService.GetLoggedUserIdAsync();
                await this.courseService.UpdateAsync(model, userId);
                return this.RedirectToAction(nameof(this.Details), new { id = model.Id });
            }
            catch (Exception ex)
            {
                return this.NotFound(ex.Message);
            }
        }

        public async Task<IActionResult> EnrollFree(int courseId)
        {
            try
            {
                var userId = await this.userService.GetLoggedUserIdAsync();
                await this.courseService.EnrollCourse(courseId, userId);

                return this.RedirectToAction(nameof(this.Details), new { id = courseId });
            }
            catch (Exception ex)
            {
                return this.BadRequest(ex.Message);
            }
        }

        public async Task<IActionResult> Buy(int id)
        {
            try
            {
                var course = await this.filterCourse.GetCourseByIdAsync<PurchaseCourseViewModel>(id);

                var gateway = this.braintreeService.GetGateway();
                var clientToken = await gateway.ClientToken.GenerateAsync();
                this.ViewData["ClientToken"] = clientToken;

                return this.View(course);
            }
            catch (Exception ex)
            {
                return this.NotFound(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Buy(PurchaseCourseViewModel model)
        {
            var gateway = this.braintreeService.GetGateway();
            var request = new TransactionRequest
            {
                Amount = model.Price,
                PaymentMethodNonce = model.Nonce,
                Options = new TransactionOptionsRequest
                {
                    SubmitForSettlement = true,
                },
            };

            var customer = await gateway.Customer.CreateAsync();
            Result<Transaction> result = await gateway.Transaction.SaleAsync(request);

            if (result.IsSuccess())
            {
                try
                {
                    var userId = await this.userService.GetLoggedUserIdAsync();
                    await this.courseService.EnrollCourse(model.Id, userId);

                    return this.RedirectToAction(nameof(this.Details), new { id = model.Id });
                }
                catch (Exception ex)
                {
                    return this.BadRequest(ex.Message);
                }
            }

            return this.View(model.Id);
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var model = await this.filterCourse.GetCourseByIdAsync<CourseViewModel>(id);
                var user = await this.userService.GetLoggedUserAsync();

                model.IsUserEnrolled = this.filterCourse.IsUserEnrolledCourse(user.Id, id);
                model.CurrentUserId = user.Id;

                var sanitizer = new HtmlSanitizer();
                model.Description = sanitizer.Sanitize(model.Description);
                model.Requirments = sanitizer.Sanitize(model.Requirments);

                return this.View(model);
            }
            catch (Exception ex)
            {
                return this.NotFound(ex.Message);
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Search(SearchViewModel model)
        {
            try
            {
                await this.courseService.SearchCourses(model);
                await LoadingBaseParameters(model);
                return this.View(CoursesView, model);
            }
            catch (Exception)
            {
                return this.RedirectToAction(EmptyView, CategoryController);
            }
        }

        private async Task LoadingBaseParameters(ImportCourseModel model)
        {
            model.Languages = await this.languageService.GetLanguagesAsSelectListItem();
            model.Categories = await this.categoryService.GetCategoryList();
            model.Difficulties = this.difficultyService.GetDifficultyList();
        }

        private async Task LoadingBaseParameters(SearchViewModel model)
        {
            model.Languages = await this.languageService.GetLanguagesAsSelectListItem();
            model.Categories = await this.categoryService.GetCategoryList();
            model.Difficulties = this.difficultyService.GetDifficultyList();
        }
    }
}

src/Web/LearnFast.Web/Controllers/VideoController.cs
namespace LearnFast.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using LearnFast.Services.Data;
    using LearnFast.Services.Data.CourseService;
    using LearnFast.Services.Data.VideoService;
    using LearnFast.Web.ViewModels.Content;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class VideoController : BaseController
    {
        private readonly IVideoService videoService;
        private readonly ICourseService courseService;
        private readonly IUserService userService;

        public VideoController(
            IVideoService videoService,
            ICourseService courseService,
            IUserService userService)
        {
            this.videoService = videoService;
            this.courseService = courseService;
            this.userService = userService;
        }

        public async Task<IActionResult> AddVideo(int courseId)
        {
            var currentUserId = await this.userService.GetLoggedUserIdAsync();
            var ownerId = await this.courseService.GetOwnerIdByCourse(courseId);

            if (currentUserId != ownerId)
            {
                return this.Forbid();
            }

            var model = new ImportVideoModel();
            model.CourseId = courseId;

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddVideo(ImportVideoModel model)
        {
            if (!this.ModelState.IsValid)
            {
                this.View(model);
            }

            try
            {
                await this.videoService.UploadVideo(model);
                return this.RedirectToAction(
                    CourseController.DetailsActionName, CourseController.CourseNameController, new { id = model.CourseId });
            }
            catch (Exception ex)
            {
                return this.BadRequest(ex.Message);
            }
        }

        public async Task<IActionResult> RemoveVideo(string videoId, int courseId)
        {
            var currentUserId = await this.userService.GetLoggedUserIdAsync();
            var ownerId = await this.courseService.GetOwnerIdByCourse(courseId);

            if (currentUserId != ownerId)
            {
                return this.Forbid();
            }

            try
            {
                await this.videoService.RemoveVideo(videoId);

                return this.RedirectToAction(
                    CourseController.DetailsActionName, CourseController.CourseNameController, new { id = courseId });
            }
            catch (Exception ex)
            {
                return this.BadRequest(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditVideo(EditVideoViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                this.View(nameof(this.Edit), model);
            }

            var currentUserId = await this.userService.GetLoggedUserIdAsync();
            var ownerId = await this.courseService.GetOwnerIdByCourse(model.CourseId);

            if (currentUserId != ownerId)
            {
                return this.NotFound();
            }

            try
            {
                await this.videoService.EditVideo(model);

                return this.RedirectToAction(
                    CourseController.DetailsActionName, CourseController.CourseNameController, new { id = model.CourseId });
            }
            catch (Exception ex)
            {
                return this.BadRequest(ex.Message);
            }
        }

        public async Task<IActionResult> Edit(EditVideoViewModel model)
        {
            var currentUserId = await this.userService.GetLoggedUserIdAsync();

            var ownerId = await this.courseService.GetOwnerIdByCourse(model.CourseId);

            if (currentUserId != ownerId)
            {
                return this.NotFound();
            }

            return this.View(nameof(this.EditVideo), model);
        }
    }
}

src/Web/LearnFast.Web/Views/Course/Buy.cshtml
@model LearnFast.Web.ViewModels.Course.PurchaseCourseViewModel

@{
    this.ViewData["Title"] = "Purchase course";
    var token = this.ViewData["ClientToken"];
}

<h1 class="alert-danger">The payment has not yet been confirmed! It is in processing!</h1>
<section>
    <form id="payment-form" method="post" asp-controller="Course" asp-action="Buy" asp-route-Price="@Model.Price" asp-route-Id="@Model.Id">
        @Html.HiddenFor(n => n.Id)
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="@Model.MainImageUrl"
                         alt="image"
                         class="img-fluid rounded-start" />
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title"><a asp-controller="Course" asp-action="Details" asp-route-id="@Model.Id">@Model.Title</a></h5>
                        <p class="card-text">
                            @Model.Category.Name
                        </p>
                        <p class="card-text">
                            <small class="text-muted"><a href="/@Model.Owner.UserName">@Model.Owner.FullName</a></small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <section>
            <div class="bt-drop-in-wrapper">
                <div id="bt-dropin"></div>
            </div>
        </section>
        @Html.HiddenFor(n => n.Nonce, new { @id = "nonce" })
        <button class="btn btn-success" type="submit"><span>Confirm payment - $@Model.Price</span></button>
    </form>
</section>


@section Scripts {
    <script src="https://js.braintreegateway.com/web/dropin/1.22.0/js/dropin.min.js"></script>
    <script>
        var client_token = "@ViewBag.ClientToken";
        var form = document.querySelector('#payment-form');

        braintree.dropin.create({
            authorization: client_token,
            container: '#bt-dropin'
        }, function (createErr, instance) {
            form.addEventListener('submit', function (event) {
                event.preventDefault();

                instance.requestPaymentMethod(function (err, payload) {
                    if (err) {
                        return;
                    }

                    document.querySelector('#nonce').value = payload.nonce;
                    form.submit();
                });
            });
        });
    </script>
}

src/Web/LearnFast.Web/Views/Course/Courses.cshtml
@model LearnFast.Web.ViewModels.Filter.SearchViewModel

@{
    this.ViewData["Title"] = "Courses";
    this.ViewData["Style"] = "courses.css";
}

<h1>@($"{Model.CategoryName} {this.ViewData["Title"]}")</h1>
<span>Category</span>
<hr />
<div>
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Category" asp-action="Index">Categories</a></li>
                    <li class="breadcrumb-item"><a>@Model.CategoryName</a></li>
                </ol>
            </nav>
        </div>
    </div>
    <div class="container">
        <div class="filter-container">
            <form asp-controller="Course" asp-action="Search" class="form-inline my-2 my-lg-0 search-form" method="get">
                <div>
                    <h5>Sorter</h5>
                    <select asp-for="SorterArgument" asp-items="@Model.Sorter" class="form-select">
                        <option disabled selected>Select sorter</option>
                    </select>
                    <span class="text-danger"></span>
                </div>
                <hr />
                <input asp-for="SearchString" class="form-control mr-sm-2" type="search" placeholder="Search by title">
                <div>
                    <hr />
                    <div>
                        <h5>Price</h5>
                        <span>From</span>
                        <input asp-for="InitialPrice" class="price form-control" type="number" min="0">
                        <br />
                        <span>To</span>
                        <input asp-for="FinalPrice" class="price form-control" type="number" min="0">
                    </div>
                    <div class="form-check form-check-inline">
                        <input asp-for="IsFree" class="form-check-input" type="checkbox" id="inlineCheckbox">
                        <label asp-for="IsFree" class="form-check-label">Free courses</label>
                    </div>
                </div>
                <a type="button" class="btn btn-danger btn-sm" asp-action="Search">Clear</a>
                <hr />
                <div>
                    <h5>Language</h5>
                    <select asp-for="LanguageId" asp-items="@Model.Languages" class="form-select">
                        <option disabled selected>Select language</option>
                    </select>
                    <span class="text-danger"></span>
                </div>
                <hr />
                <div>
                    <h5>Category</h5>
                    <select asp-for="CategoryId" asp-items="@Model.Categories" class="form-select">
                        <option disabled selected>Select category</option>
                    </select>
                    <span class="text-danger"></span>
                </div>
                <hr />
                <div>
                    <h5>Difficulty</h5>
                    <select asp-for="Difficulty" asp-items="@Model.Difficulties" class="form-select">
                        <option disabled selected>Select difficulty</option>
                    </select>
                    <span class="text-danger"></span>
                </div>
                <hr />
                <button class="btn btn-outline-success col-6" type="submit">Search</button>
            </form>
        </div>
        @if (Model.Courses.Any())
        {
            <div>
                <div class="row row-cols-1 row-cols-md-3 courses">
                    @foreach (var course in Model.Courses)
                    {
                        <a class="course-element" asp-controller="Course" asp-action="Details" asp-route-id="@course.Id">
                            <div class="col">
                                <div class="">
                                    <img class="p-3" src="@course.MainImageUrl" />
                                    <div class="title">@course.Title</div>
                                    <div class="difficulty">Difficulty: @course.Difficulty</div>
                                    @if (course.Price == 0)
                                    {
                                        <p class="price">Free course</p>
                                    }
                                    else
                                    {
                                        <div class="price">Price: @($"${course.Price:f2}")</div>
                                    }
                                </div>
                            </div>
                        </a>
                    }
                </div>
            </div>
        }
    </div>
    @if (Model.PagesCount > 1)
    {
        <div class="pagination">
            @if (Model.HasPreviousPage)
            {
                <a class="btn btn-secondary" asp-action="Search"
           asp-all-route-data="@Model.Params"
           asp-route-Page="@Model.PreviousPage">Previous</a>
            }
            @if (Model.HasNextPage)
            {
                <a class="btn btn-secondary" asp-action="Search"
           asp-all-route-data="@Model.Params"
           asp-route-Page="@Model.NextPage">Next</a>
            }
            @if (!Model.HasNextPage)
            {
                <a class="btn btn-secondary" asp-action="Search"
           asp-all-route-data="@Model.Params"
           asp-route-Page="1">First page</a>
            }
            else
            {
                <a class="btn btn-secondary" asp-action="Search"
           asp-all-route-data="@Model.Params"
           asp-route-Page="@Model.PagesCount">Last page: @Model.PagesCount</a>
            }
        </div>
    }
</div>

@section Scripts {
    <script type="module" src="/js/filter.js" asp-append-version="true"></script>
}

@section Styles {
    <link rel="stylesheet" href="/css/courses.css" asp-append-version="true">
}

src/Web/LearnFast.Web/Views/Course/Details.cshtml
@using LearnFast.Web.ViewModels.Review
@model LearnFast.Web.ViewModels.Course.CourseViewModel

@{
    this.ViewData["Title"] = "Course details";
    this.ViewData["Style"] = "details.css";
}

<section>
    <h1>@this.ViewData["Title"]</h1>
    <div class="row">
        <div class="col">
            <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Category" asp-action="Index">Categories</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Course" asp-action="Search" asp-route-categoryId="@Model.Category.Id">@Model.Category.Name</a></li>
                    <li class="breadcrumb-item"><a asp-area="" asp-controller="Course" asp-action="Details" asp-route-id="@Model.Id">@Model.Title</a></li>
                </ol>
            </nav>
        </div>
    </div>
    <h2>@Model.Category.Name / <span class="title">@Model.Title</span></h2>
    <hr />
    <div class="overview">
        <h4>Description</h4>
        <div class="description">@Html.Raw(Model.Description)</div>
        <hr />
        <h4>Overview</h4>
        <div class="additional-info">
            <div>
                <span>@Model.Sells students</span>
            </div>
            <div>Created by: <a href="/@Model.Owner.UserName">@Model.Owner.FullName</a></div>
            <div>Language: @Model.Language.Name</div>
            <div>Difficulty: @Model.Difficulty</div>
            @if (1 == 1)
            {

            }
            @if (!Model.IsUserEnrolled && !Model.IsOwner)
            {
                @if (Model.Price <= 0)
                {

                    <div class="price"><a data-bs-toggle="modal" href="" data-bs-target="#exampleModal">Free course</a></div>
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel">Enrolling course</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Do you want to enrol on the course?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a class="btn btn-primary" asp-controller="Course" asp-action="EnrollFree" asp-route-courseId="@Model.Id">Yes</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="price">@($"${Model.Price:F2}")<a asp-controller="Payment" asp-action="Buy" asp-route-courseId="@Model.Id"><i class="bi bi-bag-fill"></i></a></div>
                }
            }

            <!-- Modal -->
        </div>
    </div>
    <div class="main-image">
        <img src="@Model.MainImageUrl" accept="image/gif, image/jpeg, image/png">
    </div>
    <hr />
    <div class="requirments">
        <h4>Course requirments</h4>
        <p>
            @Html.Raw(Model.Requirments)
        </p>
    </div>
    <div>
        @if (Model.IsOwner)
        {
            <a class="btn btn-success" asp-controller="Video"
           asp-action="AddVideo"
           asp-route-courseId="@Model.Id">Add video</a>

            <a class="btn btn-success" asp-controller="Course"
           asp-action="Edit"
           asp-route-id="@Model.Id">Edit course</a>
        }
        <h4>Course content</h4>
        @if (Model.VideosCount == 0)
        {
            <div class="alert alert-info mx-auto" role="alert">
                No contents.
            </div>
        }
        else
        {
            // TODO: should don't show content on users who don't enroll in the course.
            var videos = Model.Videos.ToArray();
            <div class="accordion" id="flush">
                @for (int i = 0; i < Model.VideosCount; i++)
                {
                    var video = videos[i];
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-@i + 1">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-@i" aria-expanded="false" aria-controls="flush-@i">
                                @video.Title
                            </button>
                        </h2>
                        <div id="flush-@i" class="accordion-collapse collapse" aria-labelledby="flush-@i + 1" data-bs-parent="#flush">
                            <div class="accordion-body">
                                @if (Model.IsUserEnrolled || Model.IsOwner)
                                {
                                    <div class="row">
                                        <div class="col-8">
                                            <h5 class="border border-primary p-3">@video.Description</h5>
                                            <hr />
                                            <video src="@video.UrlPath" controls></video>
                                        </div>
                                        @if (Model.IsOwner)
                                        {
                                            <div class="col-2">
                                                <div class="accordion-body">
                                                    <a asp-area=""
                                                       asp-controller="Video"
                                                       asp-action="Edit"
                                                       asp-route-Title="@video.Title"
                                                       asp-route-UrlPath="@video.UrlPath"
                                                       asp-route-Id="@video.Id"
                                                       asp-route-Description="@video.Description"
                                                       asp-route-CourseId="@Model.Id" class="btn btn-outline-secondary">Edit video</a>
                                                </div>
                                                <div class="accordion-body">
                                                    <a asp-area=""
                                                       asp-controller="Video"
                                                       asp-action="RemoveVideo"
                                                       asp-route-videoId="@video.Id"
                                                       asp-route-courseId="@Model.Id" class="btn btn-outline-danger">Delete video</a>
                                                </div>
                                            </div>
                                        }
                                    </div>
                                }
                                else
                                {
                                    <p class="alert alert-primary">You must enroll in this course!</p>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
    </div>
    <hr />
    <div>
        <div>
            <h4>
                <a class="btn-outline-success" asp-area=""
                   asp-controller="Review"
                   asp-action="All"
                   asp-route-CourseId="@Model.Id">All</a>/Top reviews
            </h4>
            @if (!Model.IsOwner)
            {
                <a class="btn btn-success"
               asp-area=""
               asp-controller="Review"
               asp-action="Add"
               asp-route-courseId="@Model.Id">Add review</a>
            }
        </div>
        <div class="reviews">
            <hr />
            @if (this.Model.ReviewsCount == 0)
            {
                <div class="alert alert-info mx-auto" role="alert">
                    No have reviews yet.
                </div>
            }
            else
            {
                <partial name="_ReviewPartial"
                     model="new ReviewListViewModel {
                            Reviews = Model.Reviews,
                            IsSelectedReviews = true,
                            CourseId = Model.Id,
                            CurrentUserId = Model.CurrentUserId,
                            CourseOwnerId = Model.Owner.Id }" />
            }
        </div>
    </div>
</section>

@section Styles {
    <link rel="stylesheet" href="/css/details.css" asp-append-version="true">
}